--Explore all objects in the database
select * from INFORMATION_SCHEMA.tables;

--Explore all columns in the database
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers';

select distinct country from gold.dim_customers;

select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3;

select
min(start_date) as first_product_date,
max(start_date) as last_product_date
from gold.dim_products;

select
min(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff(day, min(order_date),max(order_date)) as order_range_days
from gold.fact_sales;

select
min(birth_date) as oldest_customer,
max(birth_date) as youngest_customer,
datediff(year,min(birth_date), max(birth_date)) as age_diff_youngest_oldest
from gold.dim_customers;

--Measures in the database

--Find the total sales
select sum(sales_amount) as total_sales_usd from gold.fact_sales;

--find how many items sold
select sum(quantity) as total_quantity_sold from gold.fact_sales;

--find average selling price
select avg(price) as avg_price from gold.fact_sales;

--find the total number of orders
select count(distinct(order_number)) as total_no_of_orders from gold.fact_sales;

--find the total number of customers
select count(distinct(customer_id)) as total_no_of_customers from gold.dim_customers;

--find the total number of customers that has placed an order
select count(distinct(customer_key)) as total_no_of_purchased_customers from gold.fact_sales;

-- find total customers by countries
select 
country, 
count(customer_id) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

--find total customers by gender
select
gender, 
count(customer_id) as total_customers
from gold.dim_customers
group by gender;

--find total products by category
select
category,
count(product_name) as no_of_products
from gold.dim_products
group by category
order by no_of_products desc;

--what is the average cost in each category
select
category,
avg(product_cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc;

--what is the total revenue generated for each category
select 
p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by category
order by total_revenue desc;

--find total revenue generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as sales_by_customer
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by sales_by_customer desc;

--what is the distribution of sold items accross countries
select
c.country,
sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by 
c.country
order by total_sold_items desc;

--which five product generate the highest revenue?
select top 5
p.product_name,
sum(f.sales_amount) as total_sales
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.product_name
order by total_sales desc;

--which five product is worst perfroming in terms of revenue?
select top 5
p.subcategory,
sum(f.sales_amount) as total_sales
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.subcategory
order by total_sales asc;

